[package]
name = "conway"
description = "Conway's Game Of Life implementation in rust."
authors = ["keelus"]
version = "1.0.0"
edition = "2021"
repository = "https://github.com/keelus/conway"
license = "MIT"
license-file = "LICENSE"
keywords = ["conway", "conways", "game", "life", "sdl2"]

[dependencies]
rayon = "1.8.0"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["ttf"]
